YouClear/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('youtuber.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path, include
from .views import *
from django.views.generic import TemplateView


urlpatterns = [
    path('mypage/<int:user_id>/', my_page, name="my_page"),
    # path('sign_up/', sign_up, name='sign_up'),
    # path('login/', login, name='login'),
    # path('logout/', logout, name='logout'),
    path('', include('allauth.urls')) ,
    path(
        "email-confirmation-required/",
        TemplateView.as_view(template_name="accounts/email_confirmation_required.html"),
        name="account_email_confirmation_required",
    ),
    path(
        "email-confirmation-done/",
        TemplateView.as_view(template_name="accounts/email_confirmation_done.html"),
        name="account_email_confirmation_done",
    ),
    path(
        "password/change/",
        CustomPasswordChangeView.as_view(),
        name="account_change_password",
    ),
    path("nickname/change/", change_nickname, name="account_change_nickname"),     
]

youtuber/urls.py
from django.urls import path
from .views import *

app_name='youtuber'

urlpatterns = [
    path('', index, name='index'),    
    path('youtuber/<int:youtuber_id>/', youtuber, name='youtuber'),
    path('edit_youtuber/<int:youtuber_id>/', edit_youtuber, name='edit_youtuber'),
    path('delete_youtuber/<int:youtuber_id>/', delete_youtuber, name='delete_youtuber'),
    path('add/my_youtuber/<int:youtuber_id>/', add_my_youtuber, name='add_my_youtuber'), 
    path('remove/my_youtuber/<int:youtuber_id>/', remove_my_youtuber, name='remove_my_youtuber'),
    path('my_youtuber/<int:user_id>/', my_youtuber, name='my_youtuber'),
    path('edit_my_youtuber/<int:user_id>/', edit_my_youtuber, name='edit_my_youtuber'),
    path('delete_my_youtuber/<int:youtuber_id>/', delete_my_youtuber, name='delete_my_youtuber'),
    path('my_youtuber_list/<int:user_id>/', my_youtuber_list, name='my_youtuber_list'),
    path('add/my_youtuber_list/<int:youtuber_list_id>/', add_my_youtuber_list, name='add_my_youtuber_list'), 
    path('remove/my_youtuber_list/<int:youtuber_list_id>/', remove_my_youtuber_list, name='remove_my_youtuber_list'),
    path('edit_my_youtuber_list/<int:user_id>/', edit_my_youtuber_list, name='edit_my_youtuber_list'),
    path('delete_my_youtuber_list/<int:youtuber_list_id>/', delete_my_youtuber_list, name='delete_my_youtuber_list'),
    path('youtuber_list_detail/<int:youtuber_list_id>/', youtuber_list_detail, name='youtuber_list_detail'),
    path('youtuber_list_detail/<int:youtuber_list_id>/<int:youtuber_id>', youtuber_list_detail, name='youtuber_list_detail_specific_youtuber'),
    path('category/', category, name='category'),
    path('category/<slug:tag_slug>/', category, name='category_specific'),
    path('admin_only/', admin_only, name='admin_only'),
    path('admin_only/register_youtuber/', register_youtuber, name='register_youtuber'),
    path('admin_only/register_video/', register_video, name='register_video'),
    path('youtuber_list/popular/', popular_youtuber_list, name='popular_youtuber_list'),
    path('about/', about, name='about'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .validators import validate_no_special_characters

class User(AbstractUser):
    nickname = models.CharField(
        max_length=15,
        unique=True,
        null=True,
        validators=[validate_no_special_characters],
        error_messages={"unique": "이미 사용중인 닉네임입니다."},
    )

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from .models import User


class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["nickname"]

    def signup(self, request, user):
        user.nickname = self.cleaned_data["nickname"]
        user.save()

accounts/views.py
from django.core.checks import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from youtuber.models import MyYoutuber, YoutuberList
from django.urls import reverse
from allauth.account.views import PasswordChangeView
from .models import User
from django.contrib import messages
# from django.contrib.auth.models import User
# from django.contrib import auth

@login_required
def my_page(request, user_id):

    my_youtubers = MyYoutuber.objects.filter(user=user_id, activated=True).order_by('-listed_date')
    my_youtubers_count = my_youtubers.count()
    my_youtuber_lists = YoutuberList.objects.filter(myyoutuberlist__user=user_id, myyoutuberlist__activated=True)
    my_youtuber_lists_count = my_youtuber_lists.count()

    context = {
        'my_youtuber': my_youtubers,
        'my_youtuber_count': my_youtubers_count,
        'my_youtuber_lists': my_youtuber_lists,
        'my_youtuber_lists_count': my_youtuber_lists_count
        }
    
    return render(request, 'accounts/mypage.html', context)


class CustomPasswordChangeView(PasswordChangeView):
    def get_success_url(self):
        return reverse("youtuber:index")

@login_required
def change_nickname(request):
    if request.method == 'POST':
        change_nickname = request.POST.get('change_nickname')
        try:
            user = User.objects.get(nickname=change_nickname)
            messages.info(request, '중복된 닉네임이 있습니다')
            return redirect('account_change_nickname')
        except ObjectDoesNotExist:
            request.user.nickname = change_nickname
            request.user.save()
            messages.info(request, '닉네임 변경 완료')
            return redirect('account_change_nickname')
    return render(request, 'accounts/change_nickname.html')
    


# 이전 인증 기능
# def sign_up(request):
#     context ={}

#     if request.method == 'POST':
#         if (request.POST.get('username') and 
#             request.POST.get('password') and
#             request.POST.get('password') == request.POST.get('password_check')):

#             new_user = User.objects.create_user(
#                 username = request.POST.get('username'),
#                 password = request.POST.get('password'),
#             )

#             auth.login(request, new_user)
#             return redirect('youtuber:index')
        
#         else:
#             context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

#     return render(request, 'accounts/sign_up.html', context)    
    
# def login(request):
#     context = {}

#     if request.method == 'POST':
#         if request.POST.get('username') and request.POST.get('password'):

#             user = auth.authenticate(
#             request,
#             username = request.POST.get('username'),
#             password = request.POST.get('password')
#             )

#             if user is not None:
#                 auth.login(request, user)
#                 return redirect('youtuber:index')
#             else:
#                 context['error'] = '아이디와 비밀번호를 다시 확인해주세요..'

#         else:
#             context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'
    
#     return render(request, 'accounts/login.html', context)

# def logout(request):
#     auth.logout(request)

#     return redirect('youtuber:index')

accounts/templates/accounts/change_nickname.html
{% extends "base_only_logo.html" %}

{% block title %}닉네임 변경 | YouClear{% endblock title %}

{% block content %}
<style>
    .flex-box {
        display: flex;
    }

    .overlap-alert {
        justify-content: center;
        align-items: center;
    }
</style>
    <div class="my-4">
        <h1>닉네임 변경</h1>
    </div>
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        {{ message | linebreaksbr }}
    </div>
{% endfor %}
<form method="post">
    {% csrf_token %}
    <div>
        <input class="form-control my-1" type="text" value="{{ user.nickname }}"disabled/>
    </div>
    
    <div>
        <input class="form-control my-1" type="text" placeholder="변경할 닉네임(특수문자 불가, 15자 이내)" name="change_nickname">
    </div>

    <div class="d-grid gap-2 my-1">
        <button class="btn btn-primary" type="submit">변경하기</button>
    </div>
</form>

{% endblock content %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mypage-style.css'%}?ver=20211216">
{% endblock %}

{% block content %}

<div class="container">
    <div class="category-title">
        <h2>MYPAGE</h2>
    </div>
    <div class="mypage-profile">
        <h1>Hi,{{user.nickname}}!</h1>
    </div>
    <div class="mypage-menu">
        <ul>
            <li>
                {% if user.is_superuser %}
                    <a class="mypage-list" href="{% url 'youtuber:admin_only' %}">데이터 넣기</a>
                {% endif %}
            </li>
            <li><a href="{% url 'account_change_nickname' %}">닉네임 변경</a></li>
            {% if not user.socialaccount_set.all %}
            <li><a href="{% url 'account_change_password' %}">비밀번호 변경</a></li>
            {% endif %}
            <li><a href="{% url 'youtuber:edit_my_youtuber' user.id %}">내가 찜한유투버 <span>{{my_youtuber_count}}</span></a></li>
            <li><a href="{% url 'youtuber:edit_my_youtuber_list' user.id %}">내가 찜한리스트 <span>{{my_youtuber_lists_count}}</span></a></li>
            <li><a class="mypage-list" href="{% url 'account_logout' %}">로그아웃</a></li>
        </ul>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/mypage_bak.html
{% extends "base.html" %}
{% load socialaccount %}

{% block title %}YouClear | Mypage {% endblock title %}
{% load static %}

{% block content %}
<style>
    a {
        text-decoration: none;
        color: black;
    }
    .mypage-list {
        color: black;
        font-size: larger;
        font-weight: bold;
        text-decoration: none;
    }

    .youtuber {
        display: flex;
    }

    .youtuber-name {
        font-size: small;
        font-weight: bolder;
    }

    .youtuber-dsc {
        font-size: smaller;
    }

    .profile-img {
        object-fit: cover;
        border-radius: 5%;
        width: 70px;
        height: 70px;
    }
</style>
<div class="mypage mx-5">
    <div class="my-4"><a class="mypage-list" href="{% url 'account_logout' %}">로그아웃</a></div>
    {% if user.is_superuser %}
    <div class="my-4"><a class="mypage-list" href="{% url 'youtuber:admin_only' %}">데이터 넣기</a></div>
    {% endif %}
    <div class="col-8 mypage-list">내 정보 수정</div>
    <div class="change-my-info mx-3 my-3">
        
        <div class="my-2">
            <a href="{% url 'account_change_nickname' %}">닉네임 변경</a>
        </div>

        {% if not user.socialaccount_set.all %}
        <div>
            <a href="{% url 'account_change_password' %}">비밀번호 변경</a>
        </div>
        {% endif %}
    </div>
    <div class="youtuber my-4">
        <div class="col-8 mypage-list">찜한 유투버</div>
        <div class="col-9"><a href="{% url 'youtuber:my_youtuber' user.id %}"><img
                    src="{% static 'accounts/img/more.png' %}" alt="more.png" width="25px" height="25px"></a></div>
    </div>
    <div>
        {%for youtuber in my_youtuber %}
        <a href="{% url 'youtuber:youtuber' youtuber.youtuber.id %}">
            <div class="youtuber my-2">
                <div class="mx-3">
                    <img class="profile-img" src="{{ youtuber.youtuber.profile_image.url }}"
                        alt="{{youtuber.youtuber.name}}프로필" width=95% height=85%>
                </div>
                <div>
                    <div class="my-1 youtuber-name"> {{ youtuber.youtuber.name }}</div>
                    <div class="youtuber-dsc"> {{ youtuber.youtuber.description }} </div>
                    <div class="youtuber-dsc"> #{{ youtuber.youtuber.tag.all|join:" #" }}</div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    <div class="youtuber my-4">
        <div class="col-8 mypage-list">찜한 유투버 리스트</div>
        <div class="col-9"><a href="{% url 'youtuber:my_youtuber_list' user.id %}"><img
                    src="{% static 'accounts/img/more.png' %}" alt="more.png" width="25px" height="25px"></a></div>
    </div>
    <div class="my-4"><a class="mypage-list" href="{% url 'youtuber:category' %}">카테고리</a></div>
    <div class="my-4"><a class="mypage-list" href="{% url 'youtuber:popular_youtuber_list' %}">인기리스트</a></div>
</div>
{% endblock content %}