YouClear/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('youtuber.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtuber/urls.py
from django.urls import path
from .views import *

app_name='youtuber'

urlpatterns = [
    path('', index, name='index'),    
    path('youtuber/<int:youtuber_id>/', youtuber, name='youtuber'),
    path('edit_youtuber/<int:youtuber_id>/', edit_youtuber, name='edit_youtuber'),
    path('delete_youtuber/<int:youtuber_id>/', delete_youtuber, name='delete_youtuber'),
    path('add/my_youtuber/<int:youtuber_id>/', add_my_youtuber, name='add_my_youtuber'), 
    path('remove/my_youtuber/<int:youtuber_id>/', remove_my_youtuber, name='remove_my_youtuber'),
    path('my_youtuber/<int:user_id>/', my_youtuber, name='my_youtuber'),
    path('edit_my_youtuber/<int:user_id>/', edit_my_youtuber, name='edit_my_youtuber'),
    path('delete_my_youtuber/<int:youtuber_id>/', delete_my_youtuber, name='delete_my_youtuber'),
    path('my_youtuber_list/<int:user_id>/', my_youtuber_list, name='my_youtuber_list'),
    path('add/my_youtuber_list/<int:youtuber_list_id>/', add_my_youtuber_list, name='add_my_youtuber_list'), 
    path('remove/my_youtuber_list/<int:youtuber_list_id>/', remove_my_youtuber_list, name='remove_my_youtuber_list'),
    path('edit_my_youtuber_list/<int:user_id>/', edit_my_youtuber_list, name='edit_my_youtuber_list'),
    path('delete_my_youtuber_list/<int:youtuber_list_id>/', delete_my_youtuber_list, name='delete_my_youtuber_list'),
    path('youtuber_list_detail/<int:youtuber_list_id>/', youtuber_list_detail, name='youtuber_list_detail'),
    path('youtuber_list_detail/<int:youtuber_list_id>/<int:youtuber_id>', youtuber_list_detail, name='youtuber_list_detail_specific_youtuber'),
    path('category/', category, name='category'),
    path('category/<slug:tag_slug>/', category, name='category_specific'),
    path('admin_only/', admin_only, name='admin_only'),
    path('admin_only/register_youtuber/', register_youtuber, name='register_youtuber'),
    path('admin_only/register_video/', register_video, name='register_video'),
    path('youtuber_list/popular/', popular_youtuber_list, name='popular_youtuber_list'),
    path('about/', about, name='about'),
]

youtuber/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from taggit.managers import TaggableManager
from accounts.models import User

# Create your models here.

class Youtuber(models.Model):
    profile_image = models.ImageField(upload_to="profile/", blank=True)
    name = models.CharField(max_length=100, unique=True)
    channel_id = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=30, blank=True)
    tag = TaggableManager(blank=True)
    detail_description = models.TextField(blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'youtuber'
    
    def __str__(self):
        return self.name
 
# 유투버 별 비디오
class Video(models.Model):
    youtuber_name = models.ForeignKey(Youtuber, on_delete=models.CASCADE)
    video_name = models.CharField(max_length=100)
    video_url = models.CharField(max_length=100)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering=['-upload_date', '-update_date']
        verbose_name = 'video'
    def __str__(self):
        return self.video_name
    
# 마이 유투버 
class MyYoutuber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    youtuber = models.ForeignKey(Youtuber, on_delete=models.CASCADE, blank=True)
    listed_date = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.user} | {self.youtuber}'

    class meta:
        ordering = ['-listed_date']
        verbose_name = 'myyoutuber'

# 유투버 리스트, 마이 유투버 리스트
class YoutuberList(models.Model):
    main_title = models.CharField(max_length=40)
    sub_title = models.CharField(max_length=40)
    youtubers = models.ManyToManyField(Youtuber, related_name="youtuber_list")
    list_activated = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    tag = TaggableManager(blank=True)

    def __str__(self):
        return f'{self.sub_title} {self.main_title}'
    
    class meta:
        ordering = ['-create_date', 'update_date']
    
class MyYoutuberList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    youtuber_list = models.ForeignKey(YoutuberList, on_delete=models.CASCADE, blank=True)
    listed_date = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.user} | {self.youtuber_list}'

    class meta:
        ordering = ['-listed_date']
        verbose_name = 'my_youtuber_list'

youtuber/views.py
from django import contrib
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Youtuber, YoutuberList, MyYoutuberList, MyYoutuber, Video
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from accounts.models import User
from django.contrib import messages
from YouClear.settings import MEDIA_ROOT, MEDIA_URL
from taggit.models import Tag, TaggedItem
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
# 유투브 api 사용
from .youtube_api import get_video_id_by_url, get_video_info, get_url_to_image, get_channel_info

def index(request):
    # 최신순으로 정렬(유투버 5명 / 유투버리스트 3개)
    youtubers = Youtuber.objects.all().order_by('-create_date')[0:10]
    youtuber_lists = YoutuberList.objects.all().order_by('-create_date')
    my_youtuber_lists = MyYoutuberList.objects.filter(user=request.user.id, activated=True)
    check_my_youtuber_lists = [my_list.youtuber_list for my_list in my_youtuber_lists]

    context = {
        'youtubers': youtubers, 
        'youtuber_lists': youtuber_lists,
        'check_my_youtuber_lists': check_my_youtuber_lists,
    }
    
    return render(request, 'youtuber/index.html', context)

@login_required
def youtuber(request, youtuber_id):
    try: 
        my_youtuber = MyYoutuber.objects.get(user=request.user.id, youtuber=youtuber_id, activated=True)
    except ObjectDoesNotExist:
        my_youtuber = None

    try:
        youtuber = Youtuber.objects.get(pk=youtuber_id)
        videos = Video.objects.filter(youtuber_name=youtuber_id)
        context = {'youtuber': youtuber, 'videos': videos}
    except Youtuber.DoesNotExist:
        raise Http404('유투버명을 확인해 주세요!')

    context['my_youtuber'] = my_youtuber is None

    return render(request, 'youtuber/youtuber.html', context)

@login_required
def edit_youtuber(request, youtuber_id):
    if request.user.is_superuser:
        try:
            youtuber = Youtuber.objects.get(id=youtuber_id)
        except ObjectDoesNotExist:
            return redirect('youtuber:index')
        # get 호출일 경우 수정 페이지 호출
        if request.method == 'GET':
            context = {'youtuber': youtuber}
            return render(request, 'youtuber/edit_youtuber.html', context)
        
        # Post 호출일 경우 수정 
        elif request.method == 'POST':
            profile_image = request.FILES.get('profile_image')
            if profile_image:
                youtuber.profile_image = profile_image
                
            youtuber.name = request.POST.get('youtuber_name')
            youtuber.channel_id = request.POST.get('channel_id')
            youtuber.description =request.POST.get('youtuber_dsc')
            youtuber.detail_description = request.POST.get('detail_description')
            
            youtuber.save()

            return redirect('youtuber:youtuber', youtuber_id=youtuber.id)
    else:
        return redirect('youtuber:youtuber', youtuber_id=youtuber_id)

@login_required
def delete_youtuber(request, youtuber_id):
    if request.user.is_superuser:
        try:
            youtuber = Youtuber.objects.get(id=youtuber_id)
        except ObjectDoesNotExist:
            return redirect('youtuber:youtuber', youtuber_id=youtuber_id)
        
        youtuber.delete()

        return redirect('youtuber:index')
    
    else:
        return redirect('youtuber:youtuber', youtuber_id=youtuber_id)

        
@login_required
def my_youtuber(request, user_id):
    if user_id == request.user.id:
        my_youtubers = MyYoutuber.objects.filter(user=user_id, activated=True).order_by('-listed_date')
        context = {'my_youtubers': my_youtubers}
        
        return render(request, 'youtuber/my_youtuber.html', context)
    
    return redirect('youtuber:index')

@login_required
def add_my_youtuber(request, youtuber_id):

    my_youtuber, created = MyYoutuber.objects.get_or_create(
        user= User.objects.get(pk=request.user.id),
        youtuber= Youtuber.objects.get(pk=youtuber_id),
    )
    if not created:
        my_youtuber.activated = True
        my_youtuber.listed_date = timezone.now()
        my_youtuber.save()

    return redirect('youtuber:youtuber', youtuber_id)

@login_required
def remove_my_youtuber(request, youtuber_id):
    my_youtuber = MyYoutuber.objects.get(user=request.user.id, youtuber=youtuber_id)
    my_youtuber.activated = False
    my_youtuber.save()

    return redirect('youtuber:youtuber', youtuber_id)

@login_required
def delete_my_youtuber(request, youtuber_id):
    my_youtuber = MyYoutuber.objects.get(user=request.user.id, youtuber=youtuber_id)
    my_youtuber.activated = False
    my_youtuber.save()

    return redirect('youtuber:edit_my_youtuber', request.user.id)

@login_required
def edit_my_youtuber(request, user_id):
    my_youtubers = MyYoutuber.objects.filter(user=user_id, activated=True).order_by('-listed_date')
    context = {'my_youtuber': my_youtubers}

    return render(request, 'youtuber/edit_my_youtuber.html', context)


# 유투버 리스트
@login_required
def my_youtuber_list(request, user_id):
    if user_id == request.user.id:
        my_youtuber_lists = MyYoutuberList.objects.filter(user=user_id, activated=True).order_by('-listed_date')
        context = {'my_youtuber_lists': my_youtuber_lists}
            
        return render(request, 'youtuber/my_youtuber_list.html', context)
    
    return redirect('youtuber:index')

@login_required
def add_my_youtuber_list(request, youtuber_list_id):
    my_youtuber_list, created = MyYoutuberList.objects.get_or_create(
        user= User.objects.get(pk=request.user.id),
        youtuber_list= YoutuberList.objects.get(pk=youtuber_list_id),
    )
    if not created:
        my_youtuber_list.activated = True
        my_youtuber_list.listed_date = timezone.now()
        my_youtuber_list.save()

    if "category" in request.META['HTTP_REFERER']:
        return redirect('youtuber:category')

    if "popular" in request.META['HTTP_REFERER']:
        return redirect('youtuber:popular_youtuber_list')

    return redirect('youtuber:index')


@login_required
def remove_my_youtuber_list(request, youtuber_list_id):
    my_youtuber_list = MyYoutuberList.objects.get(user=request.user.id, youtuber_list=youtuber_list_id)
    my_youtuber_list.activated = False
    my_youtuber_list.save()

    if "category" in request.META['HTTP_REFERER']:
        return redirect('youtuber:category')
    
    if "popular" in request.META['HTTP_REFERER']:
        return redirect('youtuber:popular_youtuber_list')

    return redirect('youtuber:index')


@login_required
def delete_my_youtuber_list(request, youtuber_list_id):
    my_youtuber_list = MyYoutuberList.objects.get(user=request.user.id, youtuber_list=youtuber_list_id)
    my_youtuber_list.activated = False
    my_youtuber_list.save()

    return redirect('youtuber:edit_my_youtuber_list', request.user.id)

@login_required
def edit_my_youtuber_list(request, user_id):
    my_youtuber_lists = MyYoutuberList.objects.filter(user=user_id, activated=True).order_by('-listed_date')
    context = {'my_youtuber_lists': my_youtuber_lists}

    return render(request, 'youtuber/edit_my_youtuber_list.html', context)


#  특정 유투버 영상 리스트
def _get_videos(youtuber_id):
    videos = Video.objects.filter(youtuber_name=youtuber_id)
    videos = [video for video in videos]
    return videos

@login_required
# 마이리스트 상세페이지
def youtuber_list_detail(request,youtuber_list_id, youtuber_id=None):
    youtuber_list = YoutuberList.objects.get(id=youtuber_list_id)
    youtubers = youtuber_list.youtubers.all()
    videos = []
    
    if youtuber_id == None:
        for youtuber in youtubers:
            videos += _get_videos(youtuber.id)
            # print(videos)
        context = {
            'youtuber_list_id': youtuber_list_id,
            'youtuber_list': youtuber_list,
            'youtubers': youtubers,
            'videos': videos
        }
        return render(request, 'youtuber/youtuber_list_detail.html', context)
    else:
        videos = _get_videos(youtuber_id)
        # print(videos)
        context = {
            'youtuber_list_id': youtuber_list_id,
            'youtuber_id': youtuber_id,
            'youtuber_list': youtuber_list,
            'youtubers': youtubers,
            'videos': videos
        }
        return render(request, 'youtuber/youtuber_list_detail_specific_youtuber.html', context)

@login_required
def category(request, tag_slug=None):
    youtubers = Youtuber.objects.all()
    youtuber_lists = YoutuberList.objects.all().order_by('-create_date')
    all_tags = list(Tag.objects.all().filter(taggit_taggeditem_items__content_type__id=13))
    my_youtuber_lists = MyYoutuberList.objects.filter(user=request.user.id, activated=True)
    check_my_youtuber_lists = [my_list.youtuber_list for my_list in my_youtuber_lists]
# 필터 적용 전 전체 리스트 나열
    if tag_slug == None:
        context = {
            'youtubers': youtubers, 
            'youtuber_lists': youtuber_lists,
            'check_my_youtuber_lists': check_my_youtuber_lists,
            'all_tags': all_tags,
        }
        return render(request, 'youtuber/category.html', context)

# 특정 태그로 필터 후 리스트 나열
    else:
        specific_youtuber_lists = YoutuberList.objects.filter(tag__slug__in=[tag_slug])
        # print(specific_youtuber_lists)
        context = {
            'youtubers': youtubers, 
            'youtuber_lists': youtuber_lists,
            'specific_youtuber_lists': specific_youtuber_lists,
            'check_my_youtuber_lists': check_my_youtuber_lists,
            'all_tags': all_tags,
            'specific_tag_slug': tag_slug
        }
        
        return render(request, 'youtuber/category_specific.html', context)

@login_required
def admin_only(request):
    if request.user.is_superuser:
        return render(request, 'youtuber/admin_only.html')
    else:

youtuber/templates/youtuber/admin_only.html
{% extends 'base_only_logo.html' %}

{% block content %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        {{ message | linebreaksbr }}
    </div>
{% endfor %}
<form action="{% url 'youtuber:register_youtuber' %}" , method="post">
    {% csrf_token %}

    <input class="form-control my-1" id="channel_id" type="text" name="channel_id" placeholder="채널 id를 넣어주세요">

    <input class="form-control my-1" id="youtube_api_key" type="text" name="youtube_api_key" placeholder="유투브 api Key를 넣어주세요">
    
    <div class="d-grid gap-2 mb-4">
        <button class="btn btn-primary" type="submit">유투버 등록</button>
    </div>
</form>

<form action="{% url 'youtuber:register_video' %}" , method="post">
    {% csrf_token %}
    <input class="form-control my-1" id="video_id" type="text" name="video_id" placeholder="비디오 id를 넣어주세요">
    <input class="form-control my-1" id="youtube_api_key" type="text" name="youtube_api_key" placeholder="유투브 api Key를 넣어주세요">
    
    <div class="d-grid gap-2">
        <button class="btn btn-primary" type="submit">비디오 등록</button>
    </div>
</form>
{% endblock content %}

youtuber/templates/youtuber/category.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'youtuber-style.css'%}?ver=20211216">
{% endblock %}

{% block content %}



<div class="container">
    <div class="category-title">
        <h2>CATEGORY</h2>
    </div>
    <div class="category-list">
        {%for tag in all_tags %}
        <button type="button" onclick=location.href="{% url 'youtuber:category_specific' tag.slug %}" class="btn btn-outline-secondary" style="margin-bottom: 3px;">{{ tag }}</button>
        {% endfor %}
    </div>

    <!-- 유투버 리스트  -->
    <div class="category-title">
        <h2>YOUTUBER LIST</h2>
    </div>
    {% for list in youtuber_lists %}
    <div class="youtuber-list">
        <div class="list-title-wrap">
            <div class="list-title">
                <a href="{% url 'youtuber:youtuber_list_detail' list.id %}">
                    <div class="list-sub-name">{{ list.sub_title }}</div>
                    <div class="list-title-name">{{ list.main_title }}</div>
                </a>
            </div>
            
            {% if user.is_authenticated and list in check_my_youtuber_lists %}
                <div class="list-bookmark done">
                    <a href="{% url 'youtuber:remove_my_youtuber_list' list.id%}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
            {% elif user.is_authenticated and list not in check_my_youtuber_lists %}
                <div class="list-bookmark ">
                    <a href="{% url 'youtuber:add_my_youtuber_list' list.id %}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
            {% else %}
            {% endif %}
        </div>

        <div class="list-youtuber-wrap">
            {% for youtuber in list.youtubers.all %}
            <a href="{% url 'youtuber:youtuber' youtuber.id %}">
                <div class="list-youtuber">
                    <div class="youtuber-profile-image">
                        <img src="{{ youtuber.profile_image.url }}" alt="{{youtuber.name}}프로필">
                    </div>

                    <div class="list-youtuber-content">
                        <div class="list-youtuber-name"> {{ youtuber.name }}</div>
                        <div class="list-youtuber-dsc"> {{ youtuber.description }} </div>
                        <div class="list-youtuber-tags"> #{{ youtuber.tag.all|join:" #" }}</div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>



    </div>
    
    {% endfor %}
</div>


</div>

{% endblock content %}

youtuber/templates/youtuber/category_specific.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'youtuber-style.css'%}?ver=20211216">
{% endblock %}

{% block content %}



<div class="container">
    <div class="category-title">
        <h2>CATEGORY</h2>
    </div>
    <div class="category-list">
        {% for tag in all_tags %}
            {% if tag.slug == specific_tag_slug %}
                <button type="button" onclick=location.href="{% url 'youtuber:category' %}"  class="btn btn-secondary" style="margin-bottom: 3px;">{{ tag }}</button>
            {% else %}
                <button type="button" onclick=location.href="{% url 'youtuber:category_specific' tag.slug %}" class="btn btn-outline-secondary" style="margin-bottom: 3px;">{{ tag }}</button>
            {% endif %}
        {% endfor %}
    </div>

    <!-- 유투버 리스트  -->
    <div class="category-title">
        <h2>YOUTUBER LIST</h2>
    </div>
    {% for list in specific_youtuber_lists %}
    <div class="youtuber-list">
        <div class="list-title-wrap">
            <div class="list-title">
                <a href="{% url 'youtuber:youtuber_list_detail' list.id %}">
                    <div class="list-sub-name">{{ list.sub_title }}</div>
                    <div class="list-title-name">{{ list.main_title }}</div>
                </a>
            </div>
            
            {% if user.is_authenticated %}
                {% if list in check_my_youtuber_lists %}
                <div class="list-bookmark done">
                    <a href="{% url 'youtuber:remove_my_youtuber_list' list.id%}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
                {% else %}
                <div class="list-bookmark ">
                    <a href="{% url 'youtuber:add_my_youtuber_list' list.id %}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
                {% endif %}
            {% endif %}
        </div>

        <div class="list-youtuber-wrap">
            {% for youtuber in list.youtubers.all %}
            <a href="{% url 'youtuber:youtuber' youtuber.id %}">
                <div class="list-youtuber">
                    <div class="youtuber-profile-image">
                        <img src="{{ youtuber.profile_image.url }}" alt="{{youtuber.name}}프로필">
                    </div>

                    <div class="list-youtuber-content">
                        <div class="list-youtuber-name"> {{ youtuber.name }}</div>
                        <div class="list-youtuber-dsc"> {{ youtuber.description }} </div>
                        <div class="list-youtuber-tags"> #{{ youtuber.tag.all|join:" #" }}</div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>



    </div>
    
    {% endfor %}
</div>


</div>

{% endblock content %}

youtuber/templates/youtuber/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'youtuber-style.css'%}?ver=20211216">
{% endblock %}

{% block content %}


<div class="container">
    <!-- 유투버 카테고리 -->
    <div class="youtuber_wrap">
        <div class="category-title">
            <h2>LATEST YOUTUBER</h2>
        </div>


        <!-- Swiper -->
        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
                {% for youtuber in youtubers %}
                <div class="swiper-slide">
                    <a href="{% url 'youtuber:youtuber' youtuber.id %}">
                        <img src="{{ youtuber.profile_image.url }}" width="100%" height="100%">
                        <div class="youtuber-name">
                            {{ youtuber.name }}
                        </div>
                        <div class="youtuber-tags">
                            #{{ youtuber.tag.all|join:" #" }}
                        </div>
                    </a>
                </div>
                {% endfor %}
                <div class="swiper-slide last-slide"></div>
            </div>
            <div class="swiper-pagination"></div>
        </div>


       
    </div>

    <!-- 유투버 리스트  -->
    <div class="category-title">
        <h2>LATEST YOUTUBER LIST</h2>
    </div>
    {% for list in youtuber_lists %}
    <div class="youtuber-list">
        <div class="list-title-wrap">
            <div class="list-title">
                <a href="{% url 'youtuber:youtuber_list_detail' list.id %}">
                    <div class="list-sub-name">{{ list.sub_title }}</div>
                    <div class="list-title-name">{{ list.main_title }}</div>
                </a>
            </div>
            
            {% if user.is_authenticated and list in check_my_youtuber_lists %}
                <div class="list-bookmark done">
                    <a href="{% url 'youtuber:remove_my_youtuber_list' list.id%}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
            {% elif user.is_authenticated and list not in check_my_youtuber_lists %}
                <div class="list-bookmark ">
                    <a href="{% url 'youtuber:add_my_youtuber_list' list.id %}"><i class="fas fa-bookmark fa-lg"></i></a>
                </div>
            {% else %}
            {% endif %}
        </div>

        <div class="list-youtuber-wrap">
            {% for youtuber in list.youtubers.all %}
            <a href="{% url 'youtuber:youtuber' youtuber.id %}">
                <div class="list-youtuber">
                    <div class="youtuber-profile-image">
                        <img src="{{ youtuber.profile_image.url }}" alt="{{youtuber.name}}프로필">
                    </div>

                    <div class="list-youtuber-content">
                        <div class="list-youtuber-name"> {{ youtuber.name }}</div>
                        <div class="list-youtuber-dsc"> {{ youtuber.description }} </div>
                        <div class="list-youtuber-tags"> #{{ youtuber.tag.all|join:" #" }}</div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>



    </div>
    {% endfor %}
</div>


</div>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
    var swiper = new Swiper(".mySwiper", {
        freeMode: true,
        slidesPerView: 3.5,
        spaceBetween: 0,

        breakpoints: {
          640: {
            slidesPerView: 3.5,
            spaceBetween: 0,
          },
          768: {
            slidesPerView: 4.5,
            spaceBetween: 0,
          },
          1024: {
            slidesPerView: 5.5,
            spaceBetween: 0,
          },
          1280: {
            slidesPerView: 6.5,
            spaceBetween: 0,
          },
        },
    });
   
  </script>
  
  


{% endblock content %}

youtuber/templates/youtuber/video_play.html
{% extends 'base.html'}

{% block content %}
{% endblock content}

youtuber/templates/youtuber/youtuber.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'youtuber-style.css'%}?ver=20211215">
{% endblock %}

{% block content %}


<div class="container">
    <div class="youtuber-profile">
        <div class="profile-image">
            <img src="{{ youtuber.profile_image.url }}" alt="{{youtuber.name}}프로필">
        </div>
        <div class="youtuber-summary">
            <div class="youtuber-name"> {{ youtuber.name }}</div>
            <div class="youtuber-dsc"> {{ youtuber.description }} </div>
            <div class="youtuber-tags"> #{{ youtuber.tag.all|join:" #" }}</div>
            {% if my_youtuber %}
            <a class="zzim not" href="{% url 'youtuber:add_my_youtuber' youtuber.id  %}">찜하기</a>
            {% else %}
            <a class="zzim done" href="{% url 'youtuber:remove_my_youtuber' youtuber.id %}">찜취소</a>
            {% endif %}
                    
        {% if user.is_superuser %}
        <div class="admin_only" style="font-size: small; margin-top: 3px; font-weight: bold;">
            <a href="{% url 'youtuber:edit_youtuber' youtuber.id %}">수정하기</a>
            <a href="{% url 'youtuber:delete_youtuber' youtuber.id %}">삭제하기</a>
        </div>
        {% endif %}
        </div>
    </div>
<!--
    <div class="dsc-detail">
        {{ youtuber.detail_description }}
    </div>
-->

    <div class="video-list-wrap">
        <div class="category-title video-title">
            <h2>RECOMMENDATION VIDEO</h2>
        </div>
        <div class="video-list">
            {% for video in videos %}
            <div class="video">
                <div class='embed-container'>
                    <iframe src='https://www.youtube.com/embed/{{video.video_url}}'
                    frameborder='0' allowfullscreen></iframe>
                </div>
                <div class="video-text">
                    <div class="video-name">{{video.video_name}}</div>
                    <div class="video-date">{{video.upload_date}}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}