YouClear/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('youtuber.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtuber/urls.py
from django.urls import path
from .views import *

app_name='youtuber'

urlpatterns = [
    path('', index, name='index'),    
    path('youtuber/<int:youtuber_id>/', youtuber, name='youtuber'),
    path('edit_youtuber/<int:youtuber_id>/', edit_youtuber, name='edit_youtuber'),
    path('delete_youtuber/<int:youtuber_id>/', delete_youtuber, name='delete_youtuber'),
    path('add/my_youtuber/<int:youtuber_id>/', add_my_youtuber, name='add_my_youtuber'), 
    path('remove/my_youtuber/<int:youtuber_id>/', remove_my_youtuber, name='remove_my_youtuber'),
    path('my_youtuber/<int:user_id>/', my_youtuber, name='my_youtuber'),
    path('edit_my_youtuber/<int:user_id>/', edit_my_youtuber, name='edit_my_youtuber'),
    path('delete_my_youtuber/<int:youtuber_id>/', delete_my_youtuber, name='delete_my_youtuber'),
    path('my_youtuber_list/<int:user_id>/', my_youtuber_list, name='my_youtuber_list'),
    path('add/my_youtuber_list/<int:youtuber_list_id>/', add_my_youtuber_list, name='add_my_youtuber_list'), 
    path('remove/my_youtuber_list/<int:youtuber_list_id>/', remove_my_youtuber_list, name='remove_my_youtuber_list'),
    path('edit_my_youtuber_list/<int:user_id>/', edit_my_youtuber_list, name='edit_my_youtuber_list'),
    path('delete_my_youtuber_list/<int:youtuber_list_id>/', delete_my_youtuber_list, name='delete_my_youtuber_list'),
    path('youtuber_list_detail/<int:youtuber_list_id>/', youtuber_list_detail, name='youtuber_list_detail'),
    path('youtuber_list_detail/<int:youtuber_list_id>/<int:youtuber_id>', youtuber_list_detail, name='youtuber_list_detail_specific_youtuber'),
    path('category/', category, name='category'),
    path('category/<slug:tag_slug>/', category, name='category_specific'),
    path('admin_only/', admin_only, name='admin_only'),
    path('admin_only/register_youtuber/', register_youtuber, name='register_youtuber'),
    path('admin_only/register_video/', register_video, name='register_video'),
    path('youtuber_list/popular/', popular_youtuber_list, name='popular_youtuber_list'),
    path('about/', about, name='about'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'styles.css'%}?ver=20211216">
    <link rel="stylesheet" href="{% static 'menu.css'%}">
    
    {% block style %}
    {% endblock %}
    
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
<style>
    .flex-box {
        display: flex;
    }

    h1 {
        font-family: 'Krona One', sans-serif;
        font-size: 20px;
    }
</style>
    <div class="header">
        <a href="{% url 'youtuber:index' %}">
        <div class="flex-box" style="margin-left: 20px; margin-top: 5px;">
            <div style="margin: 0; margin-top: 5px; width: 40px;"><img class="logo" src="{% static 'img/logo.png' %}" alt="logo" width="100%"></div>
            <div style="margin: 6px;"><h1>YouClear</h1></div>
        </div>
    </a>


        {% if user.is_authenticated %}
        <div class="mobilemenu_btn">
            <span class="menu ani">
              <span></span>
            </span>
        </div>
        <div class="mobile_menu" >
            <ul>
                <li><a href="{% url 'my_page' user.id %}">Mypage</a></li>
                <li><a href="{% url 'youtuber:popular_youtuber_list' %}">Popular</a></li>
                <li><a href="{% url 'youtuber:category' %}">Category</a></li>
                <li><a href="{% url 'youtuber:about' %}">About</a></li>
            </ul>
        </div>


        {% else %}
        <div>
            <a href="{% url 'account_login' %}">로그인</a>
            <a href="{% url 'account_signup' %}">회원가입</a>
        </div>
        {% endif %}


    </div>
                




        {% block content %}
        {% endblock content %}


   
  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  
  
  <script>
      $( ".mobilemenu_btn" ).click(function() {
		  $( ".mobilemenu_btn span.menu" ).toggleClass( "open" );
		  $(".mobile_menu").toggleClass("open");
	   });

  </script>


</body>
</html>

templates/base_only_logo.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css'%}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<style>
    .logo {
    font-size: xx-large;
    text-align: center;
    margin: 15% auto ;
}
</style>

<body>
    <div class="container">
        <div class="container-fluid">
            <div class="logo">
                <a href="{% url 'youtuber:index' %}">YouClear</a>
            </div>
            {% block content %}
            {% endblock content %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous"></script>
        </div>
</body>

</html>